name: "Cron Build With Quarkus Master"

on:
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Pull Quarkus Native Builder Image
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }}

      - name: Build Quarkus master
        run: git clone --depth 1 --branch master https://github.com/quarkusio/quarkus.git && cd quarkus && mvn -B clean install -DskipTests -DskipITs

      - name: Build - JVM
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT

      - name: Build - Native
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }}
