name: "Cron Build With Quarkus 1.12.x SNAPSHOT"

on:
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'amqphub/quarkus-qpid-jms' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
        graal: [ 20.3.1.2 , 21.0.0.2 ]
        include:
          # Add Java 8+15 JVM-only runs (native build only supported with Java 11 now).
          - java: 8
            graal: none
          - java: 15
            graal: none

    steps:
      - uses: actions/checkout@v2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Pull Quarkus Native Builder Image (${{ matrix.graal }})
        if: matrix.graal != 'none'
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}

      - name: Build Quarkus 1.12.x SNAPSHOT
        run: git clone --depth 1 --branch 1.12 https://github.com/quarkusio/quarkus.git && cd quarkus && echo "Current Quarkus commit:" $(git rev-parse HEAD) && mvn -B --settings ../.github/cron-maven-settings.xml clean install -DskipTests -DskipITs

      - name: Build - JVM
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT

      - name: Build - Native
        if: matrix.graal != 'none'
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}
