name: "Cron Build With Quarkus Branch"

on:
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'amqphub/quarkus-qpid-jms' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17 ]
        graal: [ 22.3 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/io/quarkus
          key: ${{ runner.os }}-cron-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-cron-maven
            ${{ runner.os }}-maven

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Pull Quarkus Native Builder Image (${{ matrix.graal }})
        if: matrix.graal != 'none'
        run: docker pull quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:${{ matrix.graal }}-java${{ matrix.java }}

      - name: Build Quarkus 3.0.x-SNAPSHOT
        env:
          MAVEN_PL: "., io.quarkus:quarkus-bom, io.quarkus:quarkus-core-deployment, io.quarkus:quarkus-arc-deployment, io.quarkus:quarkus-netty-deployment, io.quarkus:quarkus-extension-processor, io.quarkus:quarkus-bootstrap-bom, io.quarkus:quarkus-bootstrap-bom-test, io.quarkus:quarkus-extension-maven-plugin, io.quarkus:quarkus-maven-plugin, io.quarkus:quarkus-resteasy-reactive-deployment, io.quarkus:quarkus-jms-spi-deployment, io.quarkus:quarkus-junit5"
        run: |
          git clone --depth 1 --branch 3.0 https://github.com/quarkusio/quarkus.git && cd quarkus && echo "Current Quarkus commit:" $(git rev-parse HEAD)
          mvn -B -s ../.github/cron-maven-settings.xml clean install -DskipTests -DskipITs -Dformat.skip -DskipDocs -am -pl "${MAVEN_PL}"

      - name: Build - JVM
        run: mvn -B -s .github/cron-maven-settings.xml clean verify -Dquarkus-version=999-SNAPSHOT

      - name: Build - Native
        if: matrix.graal != 'none'
        run: mvn -B -s .github/cron-maven-settings.xml clean verify -Dquarkus-version=999-SNAPSHOT -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:${{ matrix.graal }}-java${{ matrix.java }}
